{% set version = "3.1.2" %}

package:
  name: libmo_unpack
  version: {{ version }}

source:
  url: https://github.com/SciTools/libmo_unpack/archive/v{{ version }}.tar.gz
  sha256: e09ef3e6f1075144acc5d6466b4ef70b2fe32ed4ab1840dd4fb7e15a40f3d370
  patches:
    - endian.patch  # [osx]
    - tests_cmakelist.patch

build:
  number: 1001
  skip: True  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - check

test:
  commands:
    - test -f ${PREFIX}/lib/libmo_unpack${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/SciTools/libmo_unpack
  license: BSD 3-Clause
  license_file: LICENSE

  summary: 'Met Office PP/FieldsFile compression schemes.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
