{% set version = "3.0" %}

package:
    name: libmo_unpack
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/SciTools/libmo_unpack/archive/v{{ version }}.tar.gz
    sha256: dc64f38ce588c8780d53e91c399cf836588e2afd7d1b7191dc286bf5eca9c75f

build:
    number: 1
    skip: True  # [win]

requirements:
    build:
        - check
        - automake
        - libtool
        - pkg-config

test:
    commands:
        - test -f ${PREFIX}/lib/libmo_unpack.a  # [not win]
        - conda inspect linkages -n _test libmo_unpack  # [not win]

about:
    home: https://github.com/SciTools/libmo_unpack
    license: BSD 3-Clause
    summary: 'Met Office PP/FieldsFile compression schemes.'

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
