{% set version = "8231" %}

package:
  name: libmo_unpack
  version: {{ version }}

source:
  url: https://github.com/SciTools/libmo_unpack/archive/v{{ version }}.tar.gz
  sha256: 96256dff98dc0b164680567d549e81acaaa4219a7cfc2f7f6fa8bb09522f670e
  patches:
    - endian.patch  # [osx]
    - tests_cmakelist.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - check

test:
  commands:
    - test -f ${PREFIX}/lib/libmo_unpack${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/SciTools/libmo_unpack
  license: BSD 3-Clause
  license_file: LICENSE

  summary: Met Office PP/FieldsFile compression schemes.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
