{% set version = "3.1.2" %}

package:
    name: libmo_unpack
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/SciTools/libmo_unpack/archive/v{{ version }}.tar.gz
    sha256: e09ef3e6f1075144acc5d6466b4ef70b2fe32ed4ab1840dd4fb7e15a40f3d370

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - check
        - automake
        - libtool
        - pkg-config

test:
    commands:
        - test -f ${PREFIX}/lib/libmo_unpack.a  # [not win]
        - conda inspect linkages -p ${PREFIX} libmo_unpack  # [not win]

about:
    home: https://github.com/SciTools/libmo_unpack
    license: BSD 3-Clause
    summary: 'Met Office PP/FieldsFile compression schemes.'

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
