appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kuM3MfIRqWZspCFmKRp9E0LrLPLiJkAXtIyOTL6A2S7wgP1usOu2r4Ecu3M6n8qdntdtDJ9Bej4EBANhHBmQO9pOrUAU3ypY0IhD0dE+QhURbgWTPdRYnOW0oKL8yEn2wL39thjJTMAxwN5TtrAyxYdCZEK9M7fPQYJds1T8XbJNc7gLXt+5CYtR+foAX8QFMySfismpk8ZRggq/nB0N/pnp7KpKZpKQCvuiXtaapQnL3QYSu7/Uo5L6aFsZBJ19yLNpyoDbgYiceZoah4ySWajdp7EXGQyabyYCXL08pftFRtR9JO8hcMUJg3VwWy/F7u8r/g2vVPdl83nua7E8HdYdvDqk3b+JxUK1CBs1NrEyHHrRGoq3NEpRpmfCgTtL4Jfq6ONycX+d6tRXkD2TUI2QkXOP/iXxQpP/euHZcwfn7GpOEWpPKltykQBJDUmK+4aS8wFj60SKzrK2dclmsCvVERz6Wj3eQyihPVXhClB+bE6W0cEtOnaSHhuWCYIk++Du35AFify1Nu2SJSNYZOgbLanWt9OP+b0/UmFem4D+KkqEohltNN9i7SMBf0b0M5ValboWZ8ChjGutePA/MC33l8SDab6M2II+SaN3Nef+IKj0OJKT8Uf016nL2pQYpHEX4LIL7AsbfBcBlxmI8KTsnaDLWYGzGRJZIP5vHXg=}
conda_forge_output_validation: true
bot:
  automerge: true
